"""your revision message

Revision ID: 2bd3ae7849e8
Revises: fd9e24e0f0b1
Create Date: 2024-09-27 06:13:43.843673

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2bd3ae7849e8"
down_revision: Union[str, None] = "fd9e24e0f0b1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "cancelled_ticket",
        sa.Column("cancelled_datetime", sa.DateTime(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("cancelled_ticket", "cancelled_datetime")
    # ### end Alembic commands ###
