"""Add email column to users

Revision ID: 3384ca247065
Revises: ec0280991a85
Create Date: 2024-09-26 23:25:10.646751

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3384ca247065"
down_revision: Union[str, None] = "ec0280991a85"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ticket_progress",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("departed_datetime", sa.DateTime(), nullable=True),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("image_url", sa.String(length=100), nullable=True),
        sa.Column("status_datetime", sa.DateTime(), nullable=True),
        sa.Column("status_code", sa.Integer(), nullable=True),
        sa.Column("priority", sa.Integer(), nullable=True),
        sa.Column("expected_datetime", sa.DateTime(), nullable=True),
        sa.Column("completed_datetime", sa.DateTime(), nullable=True),
        sa.Column("allotment_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["allotment_id"],
            ["ticket_allotment.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("ticket_progress")
    # ### end Alembic commands ###
