"""Add email column to users

Revision ID: 3a050e24c5d8
Revises: 
Create Date: 2024-09-25 22:07:23.680504

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3a050e24c5d8"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "customer",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=20), nullable=False),
        sa.Column("contact_number", sa.String(length=10), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("contact_number"),
    )
    op.create_index(op.f("ix_customer_name"), "customer", ["name"], unique=False)
    op.create_table(
        "user",
        sa.Column("id", sa.String(length=20), nullable=False),
        sa.Column("user_type", sa.Integer(), nullable=False),
        sa.Column("full_name", sa.String(length=20), nullable=False),
        sa.Column("email", sa.String(length=30), nullable=False),
        sa.Column("hashed_password", sa.String(length=100), nullable=False),
        sa.Column("mobile_number", sa.String(length=10), nullable=False),
        sa.Column("status_code", sa.Integer(), nullable=True),
        sa.Column("created_datetime", sa.DateTime(), nullable=True),
        sa.Column("supervisor_id", sa.String(length=20), nullable=True),
        sa.ForeignKeyConstraint(
            ["supervisor_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("mobile_number"),
    )
    op.create_index(op.f("ix_user_full_name"), "user", ["full_name"], unique=False)
    op.create_table(
        "ticket",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("description", sa.String(length=100), nullable=True),
        sa.Column("image_path", sa.String(length=75), nullable=True),
        sa.Column("branch_location", sa.String(length=75), nullable=True),
        sa.Column("created_datetime", sa.DateTime(), nullable=True),
        sa.Column("status_code", sa.Integer(), nullable=True),
        sa.Column("customer_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customer.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("image_path"),
    )
    op.create_table(
        "ticket_raiser",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ticket_id", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.String(length=20), nullable=True),
        sa.ForeignKeyConstraint(
            ["ticket_id"],
            ["ticket.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("ticket_raiser")
    op.drop_table("ticket")
    op.drop_index(op.f("ix_user_full_name"), table_name="user")
    op.drop_table("user")
    op.drop_index(op.f("ix_customer_name"), table_name="customer")
    op.drop_table("customer")
    # ### end Alembic commands ###
