"""your revision message

Revision ID: 4bf30361e39f
Revises: 2bd3ae7849e8
Create Date: 2024-09-27 06:50:13.871855

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "4bf30361e39f"
down_revision: Union[str, None] = "2bd3ae7849e8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ticket_progress", sa.Column("initiated_datetime", sa.DateTime(), nullable=True)
    )
    op.drop_column("ticket_progress", "status_datetime")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ticket_progress", sa.Column("status_datetime", mysql.DATETIME(), nullable=True)
    )
    op.drop_column("ticket_progress", "initiated_datetime")
    # ### end Alembic commands ###
