"""Add email column to users

Revision ID: ef1e51f95102
Revises: 3a050e24c5d8
Create Date: 2024-09-26 17:27:42.850606

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ef1e51f95102"
down_revision: Union[str, None] = "3a050e24c5d8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ticket_allotment",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ticket_id", sa.Integer(), nullable=True),
        sa.Column("allocator_id", sa.String(length=20), nullable=True),
        sa.Column("engineer_id", sa.String(length=20), nullable=True),
        sa.Column("alloted_datetime", sa.DateTime(), nullable=True),
        sa.Column("status_code", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["allocator_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["engineer_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["ticket_id"],
            ["ticket.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("ticket_allotment")
    # ### end Alembic commands ###
